sudo: true
dist: trusty
language: cpp
cache: apt

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - ninja-build
      env:
        - COMPILER=g++-6
        - WITH_NO_EXCEPTIONS=OFF
        - WITH_AWAIT=OFF
        - WITH_LIGHT_TESTS=ON

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - WITH_NO_EXCEPTIONS=OFF
        - WITH_AWAIT=OFF
        - WITH_LIGHT_TESTS=OFF

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
      env:
        - COMPILER=clang++-5.0
        - WITH_NO_EXCEPTIONS=ON
        - WITH_AWAIT=ON
        - WITH_LIGHT_TESTS=ON

install:
  - export CXX=$COMPILER
  - $CXX --version
  - chmod +x tools/travis-ci.sh

script:
  - ./tools/travis-ci.sh

notifications:
  email: false
