image:
  - Visual Studio 2017

environment:
  matrix:
    - NO_EXCEPTIONS: OFF
    - NO_EXCEPTIONS: ON

configuration:
  - Debug

platform:
  - x64

clone_script:
  - cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: cmake -H. -Bbuild -A%PLATFORM% -DTESTS_NO_EXCEPTIONS=%NO_EXCEPTIONS%

build_script:
  - cmd: cmake --build build --config %CONFIGURATION% --target ALL_BUILD -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal /maxcpucount:2 /nologo

test_script:
  - cmd: cd build
  - cmd: ctest -C %CONFIGURATION% -V .
